import random

TECH_WORDS = [
    "python",
    "rust",
    "golang",
    "java",
    "ruby",
    "kotlin",
    "swift",
    "docker",
    "git",
    "nosql",
    "redis",
    "postgres",
    "sqlite",
    "mysql",
    "mongodb",
    "graphql",
    "rest",
    "react",
    "django",
    "fastapi",
    "flask",
    "nextjs",
    "vue",
    "svelte",
    "angular",
    "html",
    "css",
    "json",
    "yaml",
    "xml",
    "markdown",
    "terminal",
    "console",
    "shell",
    "bash",
    "zsh",
    "linux",
    "macos",
    "windows",
    "kernel",
    "thread",
    "process",
    "memory",
    "buffer",
    "cache",
    "stack",
    "heap",
    "pointer",
    "variable",
    "function",
    "method",
    "class",
    "object",
    "module",
    "package",
    "library",
    "framework",
    "compiler",
    "linker",
    "interpreter",
    "debugger",
    "profiler",
    "latency",
    "throughput",
    "bandwidth",
    "network",
    "socket",
    "client",
    "server",
    "api",
    "microservice",
    "monolith",
    "cloud",
    "lambda",
    "kubernetes",
    "ansible",
    "terraform",
    "pipeline",
    "deploy",
    "release",
    "rollback",
    "logging",
    "metric",
    "tracing",
    "monitor",
    "alert",
    "security",
    "exploit",
    "firewall",
    "encryption",
    "decryption",
    "cipher",
    "token",
    "session",
    "cookie",
    "auth",
    "oauth",
    "jwt",
    "hash",
    "checksum",
    "algorithm",
    "sorting",
    "searching",
    "recursion",
    "closure",
    "decorator",
    "generator",
    "iterator",
    "coroutine",
    "asyncio",
    "callback",
    "promise",
    "future",
    "observer",
    "singleton",
    "factory",
]

GENERAL_WORDS = [
    "gravity",
    "keyboard",
    "typing",
    "practice",
    "accuracy",
    "speed",
    "victory",
    "defeat",
    "challenge",
    "champion",
    "master",
    "rookie",
    "expert",
    "legend",
    "galaxy",
    "nebula",
    "cosmos",
    "universe",
    "planet",
    "asteroid",
    "comet",
    "orbit",
    "rocket",
    "shuttle",
    "satellite",
    "eclipse",
    "solstice",
    "equinox",
    "matrix",
    "vortex",
    "portal",
    "tunnel",
    "passage",
    "horizon",
    "zenith",
    "nadir",
    "apex",
    "summit",
    "abyss",
    "canyon",
    "glacier",
    "volcano",
    "tsunami",
    "cyclone",
    "monsoon",
    "breeze",
    "tempest",
    "whisper",
    "thunder",
    "lightning",
    "shadow",
    "reflection",
    "mirage",
    "phantom",
    "specter",
    "vision",
    "dream",
    "illusion",
    "paradox",
    "enigma",
    "riddle",
    "puzzle",
    "mystery",
    "secret",
    "beacon",
    "signal",
    "radar",
    "sonar",
    "compass",
    "anchor",
    "rudder",
    "sails",
    "journey",
    "voyage",
    "odyssey",
    "quest",
    "mission",
    "venture",
    "hazard",
    "danger",
    "safety",
    "shelter",
    "oasis",
    "miracle",
    "wonder",
    "marvel",
    "spark",
    "ember",
    "flame",
    "blaze",
    "torrent",
    "cascade",
    "fountain",
]

# Combine lists for mixed mode
MIXED_WORDS = list(set(TECH_WORDS + GENERAL_WORDS))


def get_random_word(category: str = "mixed", level: int = 1) -> str:
    """
    Get a random word from the specified category.
    Filters words by length based on the current level to increase difficulty:
    - Level 1: 3-5 letters
    - Level 2: 4-7 letters
    - Level 3: 5-9 letters
    - Level 4+: 6+ letters
    """
    cat = category.lower()
    if cat == "tech":
        word_pool = TECH_WORDS
    elif cat == "general":
        word_pool = GENERAL_WORDS
    else:
        word_pool = MIXED_WORDS

    # Filter word pool by length corresponding to current level
    if level == 1:
        filtered_pool = [w for w in word_pool if 3 <= len(w) <= 5]
    elif level == 2:
        filtered_pool = [w for w in word_pool if 4 <= len(w) <= 7]
    elif level == 3:
        filtered_pool = [w for w in word_pool if 5 <= len(w) <= 9]
    else:
        filtered_pool = [w for w in word_pool if len(w) >= 6]

    # Fallback in case pool is empty (e.g. customized list with limits)
    if not filtered_pool:
        filtered_pool = word_pool

    return random.choice(filtered_pool)
